# Generated by Django 2.2.3 on 2019-07-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190717_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='consumer_name',
            new_name='name',
        ),
    ]
