# Generated by Django 2.2.3 on 2019-07-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('app', '0003_auto_20190717_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Consumer')),
            ],
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
