# Generated by Django 2.2.3 on 2019-07-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('tariff', models.CharField(max_length=20)),
            ],
        ),
    ]
