# Generated by Django 2.2.3 on 2019-07-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='User',
        ),
    ]
