# Generated by Django 2.2.3 on 2019-07-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_auto_20190706_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('value', models.IntegerField(max_length=20)),
            ],
        ),
    ]
