# Generated by Django 2.2.3 on 2019-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='value',
        ),
        migrations.AddField(
            model_name='consumption',
            name='aggregate_consumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumption',
            name='avergae_consumption',
            field=models.IntegerField(default=0),
        ),
    ]
