# Generated by Django 2.2.3 on 2019-07-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0005_auto_20190707_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='aggregate_consumption',
            new_name='aggregate',
        ),
        migrations.RenameField(
            model_name='consumption',
            old_name='average_consumption',
            new_name='average',
        ),
    ]
